"""
performance analysis for the distributed key-value store.
measures latency vs quorum and verifies data consistency.

supports two consistency modes:
- basic: last-writer-wins with race conditions
- versioned: version-based conflict resolution

usage:
    # run with default quorum (from docker-compose)
    python -m analysis.performance

    # run full quorum comparison (restarts docker for each quorum)
    python -m analysis.performance --full

    # run basic (race condition) analysis only
    python -m analysis.performance --full-basic

    # run versioned (no race condition) analysis only
    python -m analysis.performance --full-versioned

    # just check consistency
    python -m analysis.performance --consistency-only
"""

import asyncio
import json
import os
import subprocess
import sys
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any

import httpx
import matplotlib.pyplot as plt

# configuration
LEADER_URL = "http://localhost:8080"
FOLLOWER_URLS = {
    "follower1": "http://localhost:8081",
    "follower2": "http://localhost:8082",
    "follower3": "http://localhost:8083",
    "follower4": "http://localhost:8084",
    "follower5": "http://localhost:8085",
}

# test parameters
NUM_KEYS = 10
WRITES_PER_KEY = 10  # total 100 writes
CONCURRENT_BATCH_SIZE = 10

# network delay configuration (must match docker-compose)
DELAY_MIN = 0
DELAY_MAX = 1000
NUM_FOLLOWERS = 5

# project root directory
PROJECT_ROOT = Path(__file__).parent.parent


@dataclass
class BenchmarkResult:
    """result of a single benchmark run."""

    quorum: int
    total_writes: int
    successful_writes: int
    failed_writes: int
    total_time_seconds: float
    avg_latency_ms: float
    min_latency_ms: float
    max_latency_ms: float
    median_latency_ms: float
    p90_latency_ms: float
    p95_latency_ms: float


@dataclass
class ConsistencyResult:
    """
    result of a consistency check measuring race conditions.

    measures the percentage of key-value pairs that match between leader and followers.
    this captures the effect of race conditions from concurrent writes with network delays.
    """

    quorum: int
    total_keys: int
    total_comparisons: int  # keys × followers
    matching_values: int  # count where follower[key] == leader[key]
    consistency_percentage: float  # (matching / total) × 100
    per_follower_consistency: dict[str, float]  # percentage per follower


def calculate_percentile(data: list[float], percentile: float) -> float:
    """calculate the given percentile of a sorted list."""
    if not data:
        return 0.0
    sorted_data = sorted(data)
    index = (len(sorted_data) - 1) * percentile / 100
    lower = int(index)
    upper = lower + 1
    if upper >= len(sorted_data):
        return sorted_data[-1]
    weight = index - lower
    return sorted_data[lower] * (1 - weight) + sorted_data[upper] * weight


def calculate_theoretical_latency(
    quorum: int,
    n: int = NUM_FOLLOWERS,
    delay_min: float = DELAY_MIN,
    delay_max: float = DELAY_MAX,
) -> float:
    """
    calculate the theoretical expected latency for a given quorum using order statistics.

    for uniform distribution U(a, b) with n samples, the expected value of the k-th
    order statistic (k-th smallest value) is:

        E[X(k:n)] = a + (b - a) * k / (n + 1)

    where:
        - a = delay_min (minimum delay)
        - b = delay_max (maximum delay)
        - n = number of followers
        - k = quorum (we wait for the k-th fastest response)

    intuitive explanation:
        when we have 5 followers with random delays between 0 and 1000ms,
        and we wait for k of them, we're essentially waiting for the k-th fastest.

        imagine sorting 5 random numbers between 0 and 1000:
        - the 1st (fastest) is expected around 1000/6 = 167ms
        - the 2nd is expected around 2000/6 = 333ms
        - the 3rd is expected around 3000/6 = 500ms
        - the 4th is expected around 4000/6 = 667ms
        - the 5th (slowest) is expected around 5000/6 = 833ms

    args:
        quorum: number of acknowledgments required (k in the formula)
        n: number of followers (samples)
        delay_min: minimum delay (a)
        delay_max: maximum delay (b)

    returns:
        expected latency in milliseconds
    """
    # E[X(k:n)] = a + (b - a) * k / (n + 1)
    expected_latency = delay_min + (delay_max - delay_min) * quorum / (n + 1)
    return expected_latency


def write_env_file(quorum: int) -> None:
    """
    write the .env file with the specified quorum value.
    this allows docker-compose to pick up the new quorum when restarting.
    """
    env_path = PROJECT_ROOT / ".env"
    env_content = f"""# auto-generated by performance analysis script
QUORUM={quorum}
DELAY_MIN={DELAY_MIN}
DELAY_MAX={DELAY_MAX}
"""
    env_path.write_text(env_content)
    print(f"  wrote .env file with QUORUM={quorum}")


async def wait_for_services(timeout: int = 30) -> bool:
    """wait for all services to be healthy."""
    print("  waiting for services to be ready...")
    start = time.time()

    async with httpx.AsyncClient(timeout=5.0) as client:
        while time.time() - start < timeout:
            try:
                # check leader
                response = await client.get(f"{LEADER_URL}/health")
                if response.status_code == 200:
                    # check at least one follower
                    f_response = await client.get(
                        f"{FOLLOWER_URLS['follower1']}/health"
                    )
                    if f_response.status_code == 200:
                        print("  all services ready")
                        return True
            except Exception:
                pass
            await asyncio.sleep(1)

    print("  timeout waiting for services")
    return False


async def single_write(
    client: httpx.AsyncClient, key: str, value: str
) -> tuple[bool, float]:
    """
    perform a single write and measure latency.

    returns:
        tuple of (success, latency_ms)
    """
    start = time.perf_counter()
    try:
        response = await client.post(
            f"{LEADER_URL}/store/{key}",
            json={"value": value},
        )
        latency_ms = (time.perf_counter() - start) * 1000
        return response.status_code == 200, latency_ms
    except Exception as e:
        latency_ms = (time.perf_counter() - start) * 1000
        return False, latency_ms


async def single_write_versioned(
    client: httpx.AsyncClient, key: str, value: str
) -> tuple[bool, float]:
    """
    perform a single versioned write and measure latency.

    versioned writes use the ?versioned=true query parameter to enable
    version-based conflict resolution. the leader assigns a version number
    and followers reject stale writes (version <= current).

    returns:
        tuple of (success, latency_ms)
    """
    start = time.perf_counter()
    try:
        response = await client.post(
            f"{LEADER_URL}/store/{key}?versioned=true",
            json={"value": value},
        )
        latency_ms = (time.perf_counter() - start) * 1000
        return response.status_code == 200, latency_ms
    except Exception as e:
        latency_ms = (time.perf_counter() - start) * 1000
        return False, latency_ms


async def run_benchmark_basic(quorum: int) -> BenchmarkResult:
    """
    run benchmark with BASIC mode (last-writer-wins, race conditions).

    fires all 100 writes concurrently to create natural race conditions.
    10 keys × 10 writes each = 100 total writes, all fired simultaneously.

    this demonstrates the fundamental race condition problem:
    - multiple writes to the same key compete for resources
    - random network delays cause unpredictable write ordering
    - higher quorum helps but cannot eliminate race conditions

    uses unique key prefixes per quorum to allow per-quorum consistency checking.
    """
    print(f"\n--- running BASIC benchmark with quorum={quorum} ---")

    latencies: list[float] = []
    successful = 0
    failed = 0

    async with httpx.AsyncClient(timeout=60.0) as client:
        total_writes = NUM_KEYS * WRITES_PER_KEY
        print(f"  total writes: {total_writes}")
        print(
            f"  mode: BASIC (all {total_writes} writes concurrent, race conditions expected)"
        )

        start_time = time.perf_counter()

        # fire ALL writes concurrently - creates race conditions
        all_tasks = []
        for key_idx in range(NUM_KEYS):
            key = f"q{quorum}_k{key_idx}"
            for write_idx in range(WRITES_PER_KEY):
                value = f"value_{write_idx}"
                all_tasks.append(single_write(client, key, value))

        # execute all writes concurrently
        results = await asyncio.gather(*all_tasks)

        for success, latency in results:
            latencies.append(latency)
            if success:
                successful += 1
            else:
                failed += 1

        print(f"  progress: {total_writes}/{total_writes} writes (all concurrent)")

        total_time = time.perf_counter() - start_time

    avg_latency = sum(latencies) / len(latencies) if latencies else 0
    min_latency = min(latencies) if latencies else 0
    max_latency = max(latencies) if latencies else 0
    median_latency = calculate_percentile(latencies, 50)
    p90_latency = calculate_percentile(latencies, 90)
    p95_latency = calculate_percentile(latencies, 95)

    result = BenchmarkResult(
        quorum=quorum,
        total_writes=total_writes,
        successful_writes=successful,
        failed_writes=failed,
        total_time_seconds=total_time,
        avg_latency_ms=avg_latency,
        min_latency_ms=min_latency,
        max_latency_ms=max_latency,
        median_latency_ms=median_latency,
        p90_latency_ms=p90_latency,
        p95_latency_ms=p95_latency,
    )

    print(f"  completed in {total_time:.2f}s")
    print(f"  success: {successful}/{total_writes}")
    print(f"  mean latency: {avg_latency:.2f}ms")
    print(f"  median latency: {median_latency:.2f}ms")
    print(f"  p90 latency: {p90_latency:.2f}ms")
    print(f"  p95 latency: {p95_latency:.2f}ms")
    print(f"  min latency: {min_latency:.2f}ms")
    print(f"  max latency: {max_latency:.2f}ms")

    return result


async def run_benchmark_versioned(quorum: int) -> BenchmarkResult:
    """
    run benchmark with VERSIONED mode (version-based conflict resolution).

    fires all 100 writes concurrently, but uses versioned writes.
    the leader assigns incrementing version numbers, and followers reject
    writes with version <= current version.

    this demonstrates how versioning eliminates race conditions:
    - each write has a unique version number
    - out-of-order delivery is handled by rejecting stale writes
    - consistency is guaranteed regardless of network delays

    uses unique key prefixes per quorum to allow per-quorum consistency checking.
    """
    print(f"\n--- running VERSIONED benchmark with quorum={quorum} ---")

    latencies: list[float] = []
    successful = 0
    failed = 0

    async with httpx.AsyncClient(timeout=60.0) as client:
        total_writes = NUM_KEYS * WRITES_PER_KEY
        print(f"  total writes: {total_writes}")
        print(
            f"  mode: VERSIONED (all {total_writes} writes concurrent, no race conditions)"
        )

        start_time = time.perf_counter()

        # fire ALL writes concurrently - versioning handles ordering
        all_tasks = []
        for key_idx in range(NUM_KEYS):
            key = f"q{quorum}_k{key_idx}"
            for write_idx in range(WRITES_PER_KEY):
                value = f"value_{write_idx}"
                all_tasks.append(single_write_versioned(client, key, value))

        # execute all writes concurrently
        results = await asyncio.gather(*all_tasks)

        for success, latency in results:
            latencies.append(latency)
            if success:
                successful += 1
            else:
                failed += 1

        print(f"  progress: {total_writes}/{total_writes} writes (all concurrent)")

        total_time = time.perf_counter() - start_time

    avg_latency = sum(latencies) / len(latencies) if latencies else 0
    min_latency = min(latencies) if latencies else 0
    max_latency = max(latencies) if latencies else 0
    median_latency = calculate_percentile(latencies, 50)
    p90_latency = calculate_percentile(latencies, 90)
    p95_latency = calculate_percentile(latencies, 95)

    result = BenchmarkResult(
        quorum=quorum,
        total_writes=total_writes,
        successful_writes=successful,
        failed_writes=failed,
        total_time_seconds=total_time,
        avg_latency_ms=avg_latency,
        min_latency_ms=min_latency,
        max_latency_ms=max_latency,
        median_latency_ms=median_latency,
        p90_latency_ms=p90_latency,
        p95_latency_ms=p95_latency,
    )

    print(f"  completed in {total_time:.2f}s")
    print(f"  success: {successful}/{total_writes}")
    print(f"  mean latency: {avg_latency:.2f}ms")
    print(f"  median latency: {median_latency:.2f}ms")
    print(f"  p90 latency: {p90_latency:.2f}ms")
    print(f"  p95 latency: {p95_latency:.2f}ms")
    print(f"  min latency: {min_latency:.2f}ms")
    print(f"  max latency: {max_latency:.2f}ms")

    return result


async def check_consistency() -> dict[str, Any]:
    """
    verify data consistency across all nodes.
    compares all follower data with leader data.
    """
    print("\n--- checking data consistency ---")

    results: dict[str, Any] = {
        "leader_size": 0,
        "followers": {},
        "all_consistent": True,
        "details": [],
    }

    async with httpx.AsyncClient(timeout=30.0) as client:
        # get leader data
        try:
            leader_response = await client.get(f"{LEADER_URL}/store")
            leader_data = leader_response.json()
            results["leader_size"] = leader_data["size"]
            leader_store = leader_data["data"]
            print(f"  leader has {results['leader_size']} keys")
        except Exception as e:
            print(f"  failed to get leader data: {e}")
            results["error"] = str(e)
            return results

        # check each follower
        for name, url in FOLLOWER_URLS.items():
            try:
                response = await client.get(f"{url}/store")
                follower_data = response.json()
                follower_store = follower_data["data"]

                # compare with leader
                missing_keys = set(leader_store.keys()) - set(follower_store.keys())
                extra_keys = set(follower_store.keys()) - set(leader_store.keys())
                mismatched_values = []

                for key in set(leader_store.keys()) & set(follower_store.keys()):
                    if leader_store[key] != follower_store[key]:
                        mismatched_values.append(key)

                is_consistent = (
                    len(missing_keys) == 0
                    and len(extra_keys) == 0
                    and len(mismatched_values) == 0
                )

                results["followers"][name] = {
                    "size": follower_data["size"],
                    "consistent": is_consistent,
                    "missing_keys": len(missing_keys),
                    "extra_keys": len(extra_keys),
                    "mismatched_values": len(mismatched_values),
                }

                if not is_consistent:
                    results["all_consistent"] = False
                    results["details"].append(
                        f"{name}: missing={len(missing_keys)}, "
                        f"extra={len(extra_keys)}, "
                        f"mismatched={len(mismatched_values)}"
                    )

                status = "consistent" if is_consistent else "inconsistent"
                print(f"  {name}: {follower_data['size']} keys - {status}")

            except Exception as e:
                print(f"  {name}: error - {e}")
                results["followers"][name] = {"error": str(e)}
                results["all_consistent"] = False

    return results


async def check_race_condition_consistency(quorum: int) -> ConsistencyResult:
    """
    check consistency by comparing key values between leader and followers.

    measures the percentage of (key, follower) pairs where the values match.
    this captures race conditions from concurrent writes with network delays:
    - higher quorum = more followers have consistent data = higher %
    - lower quorum = more async replication = more race conditions = lower %

    args:
        quorum: the quorum value used for the benchmark (to filter keys)

    returns:
        ConsistencyResult with consistency percentage and per-follower breakdown
    """
    print(f"\n--- checking race condition consistency for quorum={quorum} ---")

    async with httpx.AsyncClient(timeout=30.0) as client:
        # get leader data
        try:
            leader_response = await client.get(f"{LEADER_URL}/store")
            leader_data = leader_response.json()
            leader_store = leader_data["data"]
        except Exception as e:
            print(f"  failed to get leader data: {e}")
            return ConsistencyResult(
                quorum=quorum,
                total_keys=0,
                total_comparisons=0,
                matching_values=0,
                consistency_percentage=0.0,
                per_follower_consistency={},
            )

        # filter keys for this quorum only (q{quorum}_k0, q{quorum}_k1, ...)
        quorum_keys = [k for k in leader_store.keys() if k.startswith(f"q{quorum}_")]
        total_keys = len(quorum_keys)

        if total_keys == 0:
            print(f"  no keys found for quorum={quorum}")
            return ConsistencyResult(
                quorum=quorum,
                total_keys=0,
                total_comparisons=0,
                matching_values=0,
                consistency_percentage=0.0,
                per_follower_consistency={},
            )

        print(f"  leader has {total_keys} keys for quorum={quorum}")

        # count matching key-value pairs across all followers
        total_comparisons = 0
        matching_values = 0
        per_follower_consistency: dict[str, float] = {}

        for name, url in FOLLOWER_URLS.items():
            try:
                response = await client.get(f"{url}/store")
                follower_data = response.json()
                follower_store = follower_data["data"]

                # count how many keys match for this follower
                follower_matches = 0
                for key in quorum_keys:
                    total_comparisons += 1
                    if leader_store.get(key) == follower_store.get(key):
                        matching_values += 1
                        follower_matches += 1

                follower_pct = (follower_matches / total_keys) * 100
                per_follower_consistency[name] = follower_pct
                print(
                    f"  {name}: {follower_matches}/{total_keys} keys match ({follower_pct:.1f}%)"
                )

            except Exception as e:
                print(f"  {name}: error - {e}")
                per_follower_consistency[name] = 0.0

        # overall consistency = matching / total comparisons
        consistency_pct = (
            (matching_values / total_comparisons) * 100
            if total_comparisons > 0
            else 0.0
        )

        print(
            f"  overall: {matching_values}/{total_comparisons} = {consistency_pct:.1f}%"
        )

        return ConsistencyResult(
            quorum=quorum,
            total_keys=total_keys,
            total_comparisons=total_comparisons,
            matching_values=matching_values,
            consistency_percentage=consistency_pct,
            per_follower_consistency=per_follower_consistency,
        )


def restart_docker(quorum: int) -> bool:
    """restart docker-compose with specific quorum."""
    print(f"\n  restarting docker with quorum={quorum}...")

    try:
        # write the .env file with new quorum
        write_env_file(quorum)

        # stop existing containers
        subprocess.run(
            ["docker-compose", "down"],
            capture_output=True,
            check=True,
            cwd=PROJECT_ROOT,
        )

        # start with new quorum (will read from .env file)
        subprocess.run(
            ["docker-compose", "up", "-d"],  # "--build"],
            capture_output=True,
            check=True,
            cwd=PROJECT_ROOT,
        )

        return True

    except subprocess.CalledProcessError as e:
        print(f"  docker command failed: {e}")
        return False
    except Exception as e:
        print(f"  failed to restart: {e}")
        return False


def plot_latency_percentiles(results: list[BenchmarkResult], output_path: str) -> None:
    """
    generate and save a single plot with mean, median, p90, and p95 latencies.
    uses different colors and line styles for each metric with a legend.
    """
    quorums = [r.quorum for r in results]
    mean_latencies = [r.avg_latency_ms for r in results]
    median_latencies = [r.median_latency_ms for r in results]
    p90_latencies = [r.p90_latency_ms for r in results]
    p95_latencies = [r.p95_latency_ms for r in results]

    plt.figure(figsize=(10, 6))

    # plot each metric with different colors and line styles
    plt.plot(
        quorums,
        mean_latencies,
        color="#2196F3",
        linestyle="-",
        linewidth=2,
        marker="o",
        markersize=8,
        label="Mean",
    )
    plt.plot(
        quorums,
        median_latencies,
        color="#4CAF50",
        linestyle="--",
        linewidth=2,
        marker="s",
        markersize=8,
        label="Median (p50)",
    )
    plt.plot(
        quorums,
        p90_latencies,
        color="#FF9800",
        linestyle="-.",
        linewidth=2,
        marker="^",
        markersize=8,
        label="p90",
    )
    plt.plot(
        quorums,
        p95_latencies,
        color="#F44336",
        linestyle=":",
        linewidth=2.5,
        marker="d",
        markersize=8,
        label="p95",
    )

    plt.xlabel("Write Quorum", fontsize=12)
    plt.ylabel("Latency (ms)", fontsize=12)
    plt.title(
        "Write Latency vs Quorum\n"
        f"(100 writes per quorum, network delay: [{DELAY_MIN}ms, {DELAY_MAX}ms])",
        fontsize=14,
    )
    plt.xticks(quorums)
    plt.legend(loc="upper left", fontsize=10)
    plt.grid(True, alpha=0.3)

    # add value annotations for mean
    for q, mean, median, p90, p95 in zip(
        quorums, mean_latencies, median_latencies, p90_latencies, p95_latencies
    ):
        # only annotate the rightmost point to avoid clutter
        if q == max(quorums):
            offset = 10
            plt.annotate(
                f"{mean:.0f}",
                (q, mean),
                textcoords="offset points",
                xytext=(offset, 0),
                ha="left",
                fontsize=9,
                color="#2196F3",
            )
            plt.annotate(
                f"{median:.0f}",
                (q, median),
                textcoords="offset points",
                xytext=(offset, 0),
                ha="left",
                fontsize=9,
                color="#4CAF50",
            )
            plt.annotate(
                f"{p90:.0f}",
                (q, p90),
                textcoords="offset points",
                xytext=(offset, 0),
                ha="left",
                fontsize=9,
                color="#FF9800",
            )
            plt.annotate(
                f"{p95:.0f}",
                (q, p95),
                textcoords="offset points",
                xytext=(offset, 0),
                ha="left",
                fontsize=9,
                color="#F44336",
            )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"  saved: {output_path}")


def calculate_theoretical_consistency(quorum: int, n: int = NUM_FOLLOWERS) -> float:
    """
    calculate the theoretical minimum consistency percentage for a given quorum.

    with quorum=K out of N followers:
    - K followers are guaranteed to have the correct value (synchronous replication)
    - remaining (N-K) followers may or may not have received async replication

    theoretical minimum = (K / N) * 100%

    in practice, actual consistency is usually higher because async replication
    often completes before the consistency check.

    args:
        quorum: number of acknowledgments required
        n: number of followers

    returns:
        theoretical minimum consistency percentage
    """
    return (quorum / n) * 100


def plot_consistency_basic(results: list[ConsistencyResult], output_path: str) -> None:
    """
    generate and save a plot showing BASIC mode consistency vs quorum.

    basic mode shows race conditions from concurrent writes with last-writer-wins.
    """
    quorums = [r.quorum for r in results]
    actual_consistency = [r.consistency_percentage for r in results]

    plt.figure(figsize=(10, 6))

    # plot actual consistency (solid line with markers)
    plt.plot(
        quorums,
        actual_consistency,
        color="#F44336",  # red for basic (race conditions)
        linestyle="-",
        linewidth=2,
        marker="o",
        markersize=8,
        label="Consistency (Basic Mode)",
    )

    plt.xlabel("Write Quorum", fontsize=12)
    plt.ylabel("Consistency (%)", fontsize=12)
    plt.title(
        "Data Consistency vs Quorum - BASIC MODE\n"
        f"(last-writer-wins, {NUM_KEYS * WRITES_PER_KEY} concurrent writes, "
        f"network delay: [{DELAY_MIN}ms, {DELAY_MAX}ms])",
        fontsize=14,
    )
    plt.xticks(quorums)
    plt.ylim(0, 105)
    plt.legend(loc="upper right", fontsize=10)
    plt.grid(True, alpha=0.3)

    # add value annotations
    for q, actual in zip(quorums, actual_consistency):
        plt.annotate(
            f"{actual:.1f}%",
            (q, actual),
            textcoords="offset points",
            xytext=(0, 10),
            ha="center",
            fontsize=9,
            color="#F44336",
        )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"  saved: {output_path}")


def plot_consistency_versioned(
    results: list[ConsistencyResult], output_path: str
) -> None:
    """
    generate and save a plot showing VERSIONED mode consistency vs quorum.

    versioned mode uses version-based conflict resolution to eliminate race conditions.
    """
    quorums = [r.quorum for r in results]
    actual_consistency = [r.consistency_percentage for r in results]

    plt.figure(figsize=(10, 6))

    # plot actual consistency (solid line with markers)
    plt.plot(
        quorums,
        actual_consistency,
        color="#4CAF50",  # green for versioned (no race conditions)
        linestyle="-",
        linewidth=2,
        marker="o",
        markersize=8,
        label="Consistency (Versioned Mode)",
    )

    plt.xlabel("Write Quorum", fontsize=12)
    plt.ylabel("Consistency (%)", fontsize=12)
    plt.title(
        "Data Consistency vs Quorum - VERSIONED MODE\n"
        f"(version-based conflict resolution, {NUM_KEYS * WRITES_PER_KEY} concurrent writes, "
        f"network delay: [{DELAY_MIN}ms, {DELAY_MAX}ms])",
        fontsize=14,
    )
    plt.xticks(quorums)
    plt.ylim(0, 105)
    plt.legend(loc="lower right", fontsize=10)
    plt.grid(True, alpha=0.3)

    # add value annotations
    for q, actual in zip(quorums, actual_consistency):
        plt.annotate(
            f"{actual:.1f}%",
            (q, actual),
            textcoords="offset points",
            xytext=(0, 10),
            ha="center",
            fontsize=9,
            color="#4CAF50",
        )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"  saved: {output_path}")


def plot_consistency_comparison(
    basic_results: list[ConsistencyResult],
    versioned_results: list[ConsistencyResult],
    output_path: str,
) -> None:
    """
    generate and save a comparison plot showing both modes on the same chart.

    compares:
    - red line: basic mode (race conditions)
    - green line: versioned mode (no race conditions)
    """
    quorums = [r.quorum for r in basic_results]
    basic_consistency = [r.consistency_percentage for r in basic_results]
    versioned_consistency = [r.consistency_percentage for r in versioned_results]

    plt.figure(figsize=(10, 6))

    # plot basic consistency (red)
    plt.plot(
        quorums,
        basic_consistency,
        color="#F44336",
        linestyle="-",
        linewidth=2,
        marker="o",
        markersize=8,
        label="Basic (Last-Writer-Wins)",
    )

    # plot versioned consistency (green)
    plt.plot(
        quorums,
        versioned_consistency,
        color="#4CAF50",
        linestyle="-",
        linewidth=2,
        marker="s",
        markersize=8,
        label="Versioned (Conflict Resolution)",
    )

    plt.xlabel("Write Quorum", fontsize=12)
    plt.ylabel("Consistency (%)", fontsize=12)
    plt.title(
        "Data Consistency Comparison: Basic vs Versioned\n"
        f"({NUM_KEYS * WRITES_PER_KEY} concurrent writes, "
        f"network delay: [{DELAY_MIN}ms, {DELAY_MAX}ms])",
        fontsize=14,
    )
    plt.xticks(quorums)
    plt.ylim(0, 105)
    plt.legend(loc="center right", fontsize=10)
    plt.grid(True, alpha=0.3)

    # add value annotations for basic
    for q, basic, versioned in zip(quorums, basic_consistency, versioned_consistency):
        plt.annotate(
            f"{basic:.0f}%",
            (q, basic),
            textcoords="offset points",
            xytext=(0, -15),
            ha="center",
            fontsize=9,
            color="#F44336",
        )
        # only annotate versioned if different from basic
        if abs(versioned - basic) > 5:
            plt.annotate(
                f"{versioned:.0f}%",
                (q, versioned),
                textcoords="offset points",
                xytext=(0, 10),
                ha="center",
                fontsize=9,
                color="#4CAF50",
            )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"  saved: {output_path}")


def generate_report(
    results: list[BenchmarkResult],
    consistency: dict[str, Any],
    consistency_results: list[ConsistencyResult] | None = None,
) -> str:
    """generate text report."""
    lines = []
    lines.append("=" * 80)
    lines.append("PERFORMANCE ANALYSIS REPORT")
    lines.append("distributed key-value store with single-leader replication")
    lines.append("=" * 80)
    lines.append("")

    lines.append("CONFIGURATION:")
    lines.append(f"  total writes per quorum: {NUM_KEYS * WRITES_PER_KEY}")
    lines.append(f"  number of keys per quorum: {NUM_KEYS}")
    lines.append(f"  writes per key: {WRITES_PER_KEY}")
    lines.append(f"  concurrent batch size: {CONCURRENT_BATCH_SIZE}")
    lines.append(f"  network delay: [{DELAY_MIN}ms, {DELAY_MAX}ms]")
    lines.append(f"  number of followers: {NUM_FOLLOWERS}")
    lines.append("")

    lines.append("LATENCY RESULTS BY QUORUM:")
    lines.append("-" * 80)
    lines.append(
        f"{'quorum':<8}{'mean (ms)':<12}{'median (ms)':<14}{'p90 (ms)':<12}{'p95 (ms)':<12}{'success':<10}"
    )
    lines.append("-" * 80)

    for r in sorted(results, key=lambda x: x.quorum):
        lines.append(
            f"{r.quorum:<8}{r.avg_latency_ms:<12.2f}{r.median_latency_ms:<14.2f}"
            f"{r.p90_latency_ms:<12.2f}{r.p95_latency_ms:<12.2f}{r.successful_writes}/{r.total_writes}"
        )

    lines.append("-" * 80)
    lines.append("")

    lines.append("PERCENTILE EXPLANATION:")
    lines.append("-" * 80)
    lines.append("  - Mean: average of all latency measurements")
    lines.append("  - Median (p50): 50% of requests completed faster than this")
    lines.append("  - p90: 90% of requests completed faster than this")
    lines.append("  - p95: 95% of requests completed faster than this (tail latency)")
    lines.append("")
    lines.append("  p90 and p95 are important for understanding worst-case behavior.")
    lines.append("  high tail latencies indicate occasional slow responses.")
    lines.append("")

    lines.append("WHY LATENCY INCREASES WITH QUORUM:")
    lines.append("-" * 80)
    lines.append("  with quorum-based replication, the leader waits for K followers")
    lines.append("  to acknowledge before responding. each follower has random delay.")
    lines.append("")
    lines.append("  - quorum=1: wait for FASTEST follower only (low latency)")
    lines.append("  - quorum=3: wait for 3rd fastest (median latency)")
    lines.append("  - quorum=5: wait for SLOWEST follower (high latency)")
    lines.append("")
    lines.append("  this is the consistency vs latency trade-off:")
    lines.append("  - higher quorum = more durable (data on more nodes)")
    lines.append("  - higher quorum = higher latency (wait for slower nodes)")
    lines.append("")

    # race condition consistency results (per quorum)
    if consistency_results:
        lines.append("CONSISTENCY BY QUORUM:")
        lines.append("-" * 80)
        lines.append(
            f"{'quorum':<8}{'consistency (%)':<18}{'matching':<15}{'total':<10}"
        )
        lines.append("-" * 80)

        for cr in sorted(consistency_results, key=lambda x: x.quorum):
            lines.append(
                f"{cr.quorum:<8}{cr.consistency_percentage:<18.1f}"
                f"{cr.matching_values:<15}{cr.total_comparisons:<10}"
            )

        lines.append("-" * 80)
        lines.append("")

        lines.append("CONSISTENCY EXPLANATION:")
        lines.append("-" * 80)
        lines.append(
            "  consistency = % of (key, follower) pairs where values match leader."
        )
        lines.append(
            "  race conditions from concurrent writes + network delays cause mismatches."
        )
        lines.append("")

    lines.append("EVENTUAL CONSISTENCY (FINAL STATE):")
    lines.append("-" * 80)
    if consistency.get("all_consistent", False):
        lines.append("  all replicas are consistent with leader")
    else:
        lines.append("  some replicas have inconsistencies:")
        for detail in consistency.get("details", []):
            lines.append(f"    - {detail}")
    lines.append("")

    lines.append(f"  leader: {consistency.get('leader_size', 'n/a')} keys")
    for name, data in consistency.get("followers", {}).items():
        if "error" in data:
            lines.append(f"  {name}: error - {data['error']}")
        else:
            status = "consistent" if data.get("consistent") else "inconsistent"
            lines.append(f"  {name}: {data.get('size', 'n/a')} keys - {status}")
    lines.append("")

    lines.append("CONSISTENCY EXPLANATION:")
    lines.append("-" * 80)
    lines.append("  semi-synchronous replication guarantees:")
    lines.append("  - data is on leader + quorum followers BEFORE write returns")
    lines.append("  - remaining followers receive data asynchronously (eventually)")
    lines.append("")

    return "\n".join(lines)


async def run_single_benchmark():
    """run benchmark with current docker configuration."""
    print("=" * 60)
    print("SINGLE BENCHMARK RUN")
    print("=" * 60)

    if not await wait_for_services():
        print("services not available. run: docker-compose up -d")
        return

    # get current quorum from health check or use default
    async with httpx.AsyncClient(timeout=10.0) as client:
        response = await client.get(f"{LEADER_URL}/health")
        health = response.json()
        print(f"leader: {health['node']}")

    # run benchmark (assume quorum=2 as default)
    result = await run_benchmark_basic(quorum=2)

    # wait for async replication to complete
    print("\nwaiting for replication to complete...")
    await asyncio.sleep(3)

    # check consistency
    consistency = await check_consistency()

    # generate report
    report = generate_report([result], consistency)
    print("\n" + report)

    # save results
    results_dir = Path("results")
    results_dir.mkdir(exist_ok=True)

    (results_dir / "report.txt").write_text(report)
    print(f"report saved to: results/report.txt")


async def run_quorum_analysis_basic():
    """
    run BASIC mode quorum analysis (1-5) - demonstrates race conditions.

    uses last-writer-wins semantics with all writes fired concurrently.
    shows how race conditions affect consistency at different quorum levels.
    """
    print("=" * 60)
    print("BASIC MODE QUORUM ANALYSIS (1-5)")
    print("(last-writer-wins, race conditions expected)")
    print("=" * 60)

    results: list[BenchmarkResult] = []
    consistency_results: list[ConsistencyResult] = []
    results_dir = Path("results")
    results_dir.mkdir(exist_ok=True)

    for quorum in range(1, 6):
        print(f"\n{'=' * 40}")
        print(f"TESTING QUORUM = {quorum} (BASIC)")
        print(f"{'=' * 40}")

        # restart docker with new quorum
        if not restart_docker(quorum):
            print(f"failed to restart docker for quorum={quorum}")
            continue

        # wait for services
        if not await wait_for_services(timeout=60):
            print(f"services not ready for quorum={quorum}")
            continue

        # run BASIC benchmark
        result = await run_benchmark_basic(quorum)
        results.append(result)

        # save intermediate benchmark result
        with open(results_dir / f"basic_quorum_{quorum}.json", "w") as f:
            json.dump(asdict(result), f, indent=2)

        # wait for replication to complete
        print("\n  waiting for replication to settle...")
        await asyncio.sleep(6)

        # check race condition consistency
        consistency_result = await check_race_condition_consistency(quorum)
        consistency_results.append(consistency_result)

        # save intermediate consistency result
        with open(results_dir / f"basic_consistency_{quorum}.json", "w") as f:
            json.dump(asdict(consistency_result), f, indent=2)

    if not results:
        print("no results collected")
        return None, None

    # check eventual consistency
    print("\n" + "=" * 60)
    print("FINAL CONSISTENCY CHECK (BASIC)")
    print("=" * 60)
    await asyncio.sleep(5)
    consistency = await check_consistency()

    # generate plots
    print("\n--- generating BASIC plots ---")
    plot_latency_percentiles(results, str(results_dir / "latency_percentiles.png"))
    if consistency_results:
        plot_consistency_basic(
            consistency_results, str(results_dir / "consistency_basic.png")
        )

    # generate report
    report = generate_report(results, consistency, consistency_results)
    print("\n" + report)

    # save results
    (results_dir / "basic_report.txt").write_text(report)
    with open(results_dir / "basic_results.json", "w") as f:
        json.dump([asdict(r) for r in results], f, indent=2)
    with open(results_dir / "basic_consistency_results.json", "w") as f:
        json.dump([asdict(r) for r in consistency_results], f, indent=2)

    print("\n" + "=" * 60)
    print("BASIC ANALYSIS COMPLETE!")
    print("=" * 60)

    return results, consistency_results


async def run_quorum_analysis_versioned():
    """
    run VERSIONED mode quorum analysis (1-5) - demonstrates conflict resolution.

    uses version-based conflict resolution where stale writes are rejected.
    shows how versioning eliminates race conditions regardless of quorum.
    """
    print("=" * 60)
    print("VERSIONED MODE QUORUM ANALYSIS (1-5)")
    print("(version-based conflict resolution)")
    print("=" * 60)

    results: list[BenchmarkResult] = []
    consistency_results: list[ConsistencyResult] = []
    results_dir = Path("results")
    results_dir.mkdir(exist_ok=True)

    for quorum in range(1, 6):
        print(f"\n{'=' * 40}")
        print(f"TESTING QUORUM = {quorum} (VERSIONED)")
        print(f"{'=' * 40}")

        # restart docker with new quorum
        if not restart_docker(quorum):
            print(f"failed to restart docker for quorum={quorum}")
            continue

        # wait for services
        if not await wait_for_services(timeout=60):
            print(f"services not ready for quorum={quorum}")
            continue

        # run VERSIONED benchmark
        result = await run_benchmark_versioned(quorum)
        results.append(result)

        # save intermediate benchmark result
        with open(results_dir / f"versioned_quorum_{quorum}.json", "w") as f:
            json.dump(asdict(result), f, indent=2)

        # wait for replication to complete
        print("\n  waiting for replication to settle...")
        await asyncio.sleep(6)

        # check race condition consistency
        consistency_result = await check_race_condition_consistency(quorum)
        consistency_results.append(consistency_result)

        # save intermediate consistency result
        with open(results_dir / f"versioned_consistency_{quorum}.json", "w") as f:
            json.dump(asdict(consistency_result), f, indent=2)

    if not results:
        print("no results collected")
        return None, None

    # check eventual consistency
    print("\n" + "=" * 60)
    print("FINAL CONSISTENCY CHECK (VERSIONED)")
    print("=" * 60)
    await asyncio.sleep(5)
    consistency = await check_consistency()

    # generate plots
    print("\n--- generating VERSIONED plots ---")
    plot_latency_percentiles(results, str(results_dir / "latency_percentiles.png"))
    if consistency_results:
        plot_consistency_versioned(
            consistency_results, str(results_dir / "consistency_versioned.png")
        )

    # generate report
    report = generate_report(results, consistency, consistency_results)
    print("\n" + report)

    # save results
    (results_dir / "versioned_report.txt").write_text(report)
    with open(results_dir / "versioned_results.json", "w") as f:
        json.dump([asdict(r) for r in results], f, indent=2)
    with open(results_dir / "versioned_consistency_results.json", "w") as f:
        json.dump([asdict(r) for r in consistency_results], f, indent=2)

    print("\n" + "=" * 60)
    print("VERSIONED ANALYSIS COMPLETE!")
    print("=" * 60)

    return results, consistency_results


async def run_full_quorum_analysis():
    """
    run complete quorum comparison (1-5) for BOTH basic and versioned modes.

    this function:
    1. runs basic mode analysis (race conditions)
    2. runs versioned mode analysis (conflict resolution)
    3. generates comparison plot showing both modes
    """
    print("=" * 60)
    print("FULL QUORUM ANALYSIS - BASIC + VERSIONED")
    print("=" * 60)

    results_dir = Path("results")
    results_dir.mkdir(exist_ok=True)

    # run basic analysis
    print("\n" + "#" * 60)
    print("# PHASE 1: BASIC MODE")
    print("#" * 60)
    basic_results, basic_consistency = await run_quorum_analysis_basic()

    # run versioned analysis
    print("\n" + "#" * 60)
    print("# PHASE 2: VERSIONED MODE")
    print("#" * 60)
    versioned_results, versioned_consistency = await run_quorum_analysis_versioned()

    # generate comparison plot
    if basic_consistency and versioned_consistency:
        print("\n--- generating COMPARISON plot ---")
        plot_consistency_comparison(
            basic_consistency,
            versioned_consistency,
            str(results_dir / "consistency_comparison.png"),
        )

    print("\n" + "=" * 60)
    print("FULL ANALYSIS COMPLETE!")
    print("=" * 60)
    print("\nfiles saved in results/ directory:")
    print("  - consistency_basic.png      (basic mode - race conditions)")
    print("  - consistency_versioned.png  (versioned mode - no race conditions)")
    print("  - consistency_comparison.png (side-by-side comparison)")
    print("  - latency_percentiles.png    (latency metrics)")
    print("  - basic_report.txt           (basic mode report)")
    print("  - versioned_report.txt       (versioned mode report)")


async def run_consistency_check():
    """run consistency check only."""
    print("=" * 60)
    print("CONSISTENCY CHECK")
    print("=" * 60)

    if not await wait_for_services():
        print("services not available")
        return

    consistency = await check_consistency()

    if consistency.get("all_consistent"):
        print("\n all replicas are consistent!")
    else:
        print("\n inconsistencies found:")
        for detail in consistency.get("details", []):
            print(f"  - {detail}")


def main():
    """main entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="performance analysis for distributed kv store"
    )
    parser.add_argument(
        "--full",
        action="store_true",
        help="run full analysis (both basic and versioned modes)",
    )
    parser.add_argument(
        "--full-basic",
        action="store_true",
        help="run basic mode analysis only (race conditions)",
    )
    parser.add_argument(
        "--full-versioned",
        action="store_true",
        help="run versioned mode analysis only (conflict resolution)",
    )
    parser.add_argument(
        "--consistency-only",
        action="store_true",
        help="only check data consistency",
    )

    args = parser.parse_args()

    if args.consistency_only:
        asyncio.run(run_consistency_check())
    elif args.full_basic:
        asyncio.run(run_quorum_analysis_basic())
    elif args.full_versioned:
        asyncio.run(run_quorum_analysis_versioned())
    elif args.full:
        asyncio.run(run_full_quorum_analysis())
    else:
        asyncio.run(run_single_benchmark())


if __name__ == "__main__":
    main()
